services:
  - type: web
    name: kids-bible-church
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app -b 0.0.0.0:10000"
    envVars:
      - key: PORT
        value: 10000
